[project]
name = "tensorrt-gpt2"
version = "0.1.0"
description = "GPT-2 with TensorRT optimization"
requires-python = "==3.11.*"
dependencies = [
    "torch",
    "transformers",
    "torch_tensorrt",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu130"

[tool.uv.sources]
torch = { index = "pytorch-nightly" }
torch_tensorrt = { index = "pytorch-nightly" }

[tool.uv]
prerelease = "allow"
